module:
  imports:
    - path: github.com/jgthms/bulma
      mounts:
      - source: .
        target: assets/bulma

    - path: github.com/jloh/bulma-prefers-dark
      mounts:
      - source: .
        target: assets/bulma-prefers-dark
