baseURL: https://realorangeone.github.io/hugo-theme-notes/
title: Hugo Theme Notes
enableGitInfo: true

cleanDestinationDir: true

module:
  imports:
    - path: github.com/RealOrangeOne/hugo-theme-notes
