name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v2
        with:
          version: latest
          extended: true
          args: -s exampleSite --minify --verbose
